### PR TITLE
chore: deprecated primaryLocation and unused Locations[] fields

### PR DESCRIPTION
**Pull request by tmsavage**
The query fields primaryLocation and Locations[] have been deprecated, meaning, removed from the GraphQL database. Locations[] was not being used, while primaryLocation was only used under the spec file `weather_spec.rb`. This file's test query was updated. All queries for a location given a name have been using the field location(cityName). The purpose of this PR is to eliminate redundancy on similar ways to query a location.

### CODE REVIEW

**Review by cbarber — COMMENTED** [review]
Nit: technically not a bug. Can we split this into two commits, one for `locations` and one for `primaryLocation`?

**Comment by tmsavage** [comment]
> Nit: technically not a bug. Can we split this into two commits, one for `locations` and one for `primaryLocation`?

@cbarber Would you call this a feature?

**Comment by cbarber** [comment]
Probably a chore or feat.

**Comment by bencates** [comment]
yup, `chore`

**Review by bencates — APPROVED** [review]
image
:heart: Always a nice thing to see on a PR.

**Review by chewnoill — APPROVED** [review]
🚀

**Comment by cbarber** [comment]
You renamed the PR not the commit :(

**Pull request merged**
