### PR TITLE
[doc] add docker instructions

### PR DESCRIPTION
**Pull request by chewnoill**
remove all conflicting instructions

### CODE REVIEW

**Review by cbarber — CHANGES_REQUESTED** [review]
Docker (in its current state) isn't a viable development environment.

**Comment by chewnoill** [comment]
what do you mean? It works fine and is simpler

**Comment by cbarber** [comment]
* https://www.pivotaltracker.com/story/show/178379582
* https://www.pivotaltracker.com/story/show/178379652

**Comment by chewnoill** [comment]
https://www.pivotaltracker.com/n/projects/2176655/stories/178379582
Why is this blocking?

https://www.pivotaltracker.com/n/projects/2176655/stories/178379652
This should work as expected already: `docker-compose exec web rails c`

**Pull request closed without merging**
