### PR TITLE
fix: follow compiler lint warnings

### PR DESCRIPTION
**Pull request by RVRX**
Fixing some compiler warnings on unused variables.

### CODE REVIEW

**Review by force10269 — COMMENTED** [review]
This may be unrelated, but can we tack on a fix for the warning we get from the unused import of `Ecto.Changeset` in `slack_channel_names.ex`? I've been getting that on compilations

**Comment by RVRX** [comment]
> These fixes seem to work. This may be unrelated, but can we tack on a fix for the warning we get from the unused import of `Ecto.Changeset` in `slack_channel_names.ex`? I've been getting that on compilations

Yeah that would fit in this PR. Where/when are you seeing that warning though, @force10269 not sure I've seen it? Just wanna make sure I'm getting all the current lint errors.

**Comment by force10269** [comment]
> > These fixes seem to work. This may be unrelated, but can we tack on a fix for the warning we get from the unused import of `Ecto.Changeset` in `slack_channel_names.ex`? I've been getting that on compilations
> 
> Yeah that would fit in this PR. Where/when are you seeing that warning though, @force10269 not sure I've seen it? Just wanna make sure I'm getting all the current lint errors.

I saw it when I ran `mix test` for the first time I checked into your branch, so it should be there. You can also try `mix compile --force` and there should be something there

**Review by chewnoill — APPROVED** [review]
🚀

**Pull request merged**
