### PR TITLE
chore: Resolve node-fetch vulnerability

### PR DESCRIPTION
**Pull request by Aceba1**
- Bump eslint-plugin-graphql to 4.0.0

### CODE REVIEW

**Comment by aaddaamm** [comment]
are there any linting issues after this version bump?

**Comment by Aceba1** [comment]
It functions just the same 👍

Only difference I can find is the change of a npm script here: https://github.com/apollographql/eslint-plugin-graphql/commit/faef1fd1e5c88f16f7b9ccf23da33ca3e138557b

**Comment by aaddaamm** [comment]
so if we run the linter after this version bump we don't get any new linting warnings/errors?

**Comment by Aceba1** [comment]
That's correct

**Review by aaddaamm — APPROVED** [review]

**Pull request merged**
